export const logoTitle = "login_logo"
export const loginUsernameField = "username"
export const loginPasswordField = "password"
export const loginButton = "login-button"
export const errorAlert = "error"
export const errorButton = "error-button"